### ISSUE TITLE
Viewer 3D: antialiasing at buffer level.

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [PauloCarvalhoRJ/gammaray#154]
The current antialiasing with render::SetFXAA is not good as antialiasing in buffer.

**Comment by gogo40** [comment]
Did fixed the remaining rendering problems?

**Comment by PauloCarvalhoRJ** [comment]
Oh, it's working actually.  As you know, you can do antialiasing with several different techniques.  The one I enabled is very fast, but not the best looking one.  I think the resampling technique works best.  I still don't know how to use it with the `QVTKOpenGLWidget` class.

**Comment by PauloCarvalhoRJ** [comment]
`_vtkwidget->GetRenderWindow()->SetAAFrames(5);` gives the best visual result, but it is slow and is deprecated API.

**Comment by PauloCarvalhoRJ** [comment]
Added antialiasing config that improved rendering a bit.  More research should be done with the `vtkFXAAOptions` object or possibly adding a 3D rendering configuration dialog.
