### ISSUE TITLE
SVD: grid viewer must be XY, XZ, YZ instead of a full 3D viewer.

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [PauloCarvalhoRJ/gammaray#157]

**Comment by gogo40** [comment]
Also, the image doesn`t need to be full. We can reduce significantly the image resolution and add a button to zoom in and zoom out.

**Comment by PauloCarvalhoRJ** [comment]
True.  I'm studying VTK how can we do a sample plot of the factors in the SVD analysis dialog.
