### ISSUE TITLE
GammaRay 4.5 and 4.5.1 on Windows 7 : Won´t start : Missing libvtkImagingStencil-8.1.dll

### ISSUE THREAD

**Issue by fredrocks** [PauloCarvalhoRJ/gammaray#195]
Extracted from zipfile 
Note that GammaRay 4.3 works OK and does not have this dll dependence.

**Comment by PauloCarvalhoRJ** [comment]
True.  That dependency was introduced in 4.5.  My local deploy directory has it.  I forgot to include it in the ZIP.  Notice that 4.5.1 is just an update (just the EXE).  You need to download in deflate de ZIP of version 4.5 again.  Thanks for the heads up.  Please, inform whether you were able to run the program.

**Comment by fredrocks** [comment]
Hi Paulo.  Thanks.  Yes, the new zip works fine (both for 4.5 and 4.5.1).  regards, Fred
