### ISSUE TITLE
vtkParaviewScalarBar may not compile or function with VTK 9.

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [PauloCarvalhoRJ/gammaray#262]
It may cause a crash according to this issue:  https://github.com/embeddedmz/ParaViewScalarBarWidget/issues/1

**Comment by PauloCarvalhoRJ** [comment]
The crashes may be caused by missing return statements in some of the methods in the class or its related ones.

**Comment by AhmedShawi** [comment]
Hi @PauloCarvalhoRJ , did you find a solution for this?  Currently getting these errors:
![image](https://user-images.githubusercontent.com/40696191/133064789-1cc48b8f-ceba-439d-b9d1-077152c7b68f.png)

**Comment by PauloCarvalhoRJ** [comment]
Hello @AhmedShawi .  Eh... sorry, I didn't have time to move to VTK9 yet.  😞

**Comment by PauloCarvalhoRJ** [comment]
@AhmedShawi , I started work on this.  I'm getting lots of compilation errors with VTK 9.1 as expected.

**Comment by PauloCarvalhoRJ** [comment]
The entire planet uses `const char*` and the VTK guys use `const unsigned char*` for text strings...  It's a pain do find replacements for functions like strlen, strcpy, etc... *sigh*.

**Comment by PauloCarvalhoRJ** [comment]
@AhmedShawi , `vtkParaviewScalarBar` is now working for me:
![image](https://user-images.githubusercontent.com/6398896/156845687-b6669dfa-5ef1-483e-9e07-81141ef881eb.png)

It's small due to 4K issue, but the widget is working as expected.

This is the version working with VTK 9 (not merged to master yet): https://github.com/PauloCarvalhoRJ/gammaray/tree/Upgrade_to_VTK9.1/imagejockey/paraviewscalarbar
